
version: '3.4'

services:
  vault:
    hostname: vault
    container_name: vault
    image: hashicorp/vault:1.16.0
    restart: always
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_API_ADDR: "http://0.0.0.0:8200"
    ports:
      - "8200:8200"
    volumes:
      - ./volumes/vault/data/:/vault/config:rw

    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config /vault/config/config.json